# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kgraphviewer
confinement: strict
grade: stable
base: core24
adopt-info: kgraphviewer
apps:
  kgraphviewer:
    extensions:
      - kde-neon-6
    common-id: org.kde.kgraphviewer.desktop
    desktop: usr/share/applications/org.kde.kgraphviewer.desktop
    command: usr/bin/kgraphviewer
    plugs:
      - home
      - audio-playback
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kgraphviewer
    bus: session
parts:
  kgraphviewer:
    parse-info:
      - usr/share/metainfo/org.kde.kgraphviewer.appdata.xml
    plugin: cmake
    build-packages:
      - libgraphviz-dev
      - libboost-dev
    stage-packages:
      - libcdt5
      - libcgraph6
      - libgvc6
      - libltdl7
      - libpathplan4
      - graphviz
    source: .
    source-type: local
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/doc/*"
      - "-usr/share/man/*"
      - "-usr/bin/X11"
      - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
      - "-usr/lib/aspell/*"
      - "-usr/share/lintian"
  gpu-2404:
    after: [kgraphviewer]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kgeotag
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

